language: php

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

notifications:
  email: false

php:
  - 7.3
  - 7.4

matrix:
  fast_finish: true

install:
  - make install

script:
  - make unit
  - make integration